server:
  context-path: /web
  port: 9100

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: "jdbc:mysql://mysql_db:3306/spring_db"
    username: admin
    password: password
